# Generated by Django 6.0.7 on 2026-07-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="is_public",
            field=models.BooleanField(default=False, verbose_name="Публичная"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="periodicity",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Периодичность (дни)"
            ),
        ),
    ]
