# Generated by Django 6.0.7 on 2026-07-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_alter_habit_is_public_alter_habit_periodicity"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="last_notification",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата последнего уведомления"
            ),
        ),
    ]
